
package com.mkyong.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWorldImpl2Service", targetNamespace = "http://ws.mkyong.com/", wsdlLocation = "http://localhost:9998/ws/hello?wsdl")
public class HelloWorldImpl2Service
    extends Service
{

    private final static URL HELLOWORLDIMPL2SERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWORLDIMPL2SERVICE_EXCEPTION;
    private final static QName HELLOWORLDIMPL2SERVICE_QNAME = new QName("http://ws.mkyong.com/", "HelloWorldImpl2Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9998/ws/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWORLDIMPL2SERVICE_WSDL_LOCATION = url;
        HELLOWORLDIMPL2SERVICE_EXCEPTION = e;
    }

    public HelloWorldImpl2Service() {
        super(__getWsdlLocation(), HELLOWORLDIMPL2SERVICE_QNAME);
    }

    public HelloWorldImpl2Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWORLDIMPL2SERVICE_QNAME, features);
    }

    public HelloWorldImpl2Service(URL wsdlLocation) {
        super(wsdlLocation, HELLOWORLDIMPL2SERVICE_QNAME);
    }

    public HelloWorldImpl2Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWORLDIMPL2SERVICE_QNAME, features);
    }

    public HelloWorldImpl2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldImpl2Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWorld2
     */
    @WebEndpoint(name = "HelloWorldImpl2Port")
    public HelloWorld2 getHelloWorldImpl2Port() {
        return super.getPort(new QName("http://ws.mkyong.com/", "HelloWorldImpl2Port"), HelloWorld2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorld2
     */
    @WebEndpoint(name = "HelloWorldImpl2Port")
    public HelloWorld2 getHelloWorldImpl2Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.mkyong.com/", "HelloWorldImpl2Port"), HelloWorld2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWORLDIMPL2SERVICE_EXCEPTION!= null) {
            throw HELLOWORLDIMPL2SERVICE_EXCEPTION;
        }
        return HELLOWORLDIMPL2SERVICE_WSDL_LOCATION;
    }

}
