
package com.turkcell.balanceinquiry.ejb.impl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BalanceInquiryImplService", targetNamespace = "http://impl.ejb.balanceinquiry.turkcell.com/", wsdlLocation = "META-INF/wsdl/BalanceInquiryImplService.wsdl")
public class BalanceInquiryImplService
    extends Service
{

    private final static URL BALANCEINQUIRYIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BALANCEINQUIRYIMPLSERVICE_EXCEPTION;
    private final static QName BALANCEINQUIRYIMPLSERVICE_QNAME = new QName("http://impl.ejb.balanceinquiry.turkcell.com/", "BalanceInquiryImplService");

    static {
        BALANCEINQUIRYIMPLSERVICE_WSDL_LOCATION = com.turkcell.balanceinquiry.ejb.impl.BalanceInquiryImplService.class.getClassLoader().getResource("META-INF/wsdl/BalanceInquiryImplService.wsdl");
        WebServiceException e = null;
        if (BALANCEINQUIRYIMPLSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/BalanceInquiryImplService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        BALANCEINQUIRYIMPLSERVICE_EXCEPTION = e;
    }

    public BalanceInquiryImplService() {
        super(__getWsdlLocation(), BALANCEINQUIRYIMPLSERVICE_QNAME);
    }

    public BalanceInquiryImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BALANCEINQUIRYIMPLSERVICE_QNAME, features);
    }

    public BalanceInquiryImplService(URL wsdlLocation) {
        super(wsdlLocation, BALANCEINQUIRYIMPLSERVICE_QNAME);
    }

    public BalanceInquiryImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BALANCEINQUIRYIMPLSERVICE_QNAME, features);
    }

    public BalanceInquiryImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BalanceInquiryImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BalanceInquiryImpl
     */
    @WebEndpoint(name = "BalanceInquiryImplPort")
    public BalanceInquiryImpl getBalanceInquiryImplPort() {
        return super.getPort(new QName("http://impl.ejb.balanceinquiry.turkcell.com/", "BalanceInquiryImplPort"), BalanceInquiryImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BalanceInquiryImpl
     */
    @WebEndpoint(name = "BalanceInquiryImplPort")
    public BalanceInquiryImpl getBalanceInquiryImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ejb.balanceinquiry.turkcell.com/", "BalanceInquiryImplPort"), BalanceInquiryImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BALANCEINQUIRYIMPLSERVICE_EXCEPTION!= null) {
            throw BALANCEINQUIRYIMPLSERVICE_EXCEPTION;
        }
        return BALANCEINQUIRYIMPLSERVICE_WSDL_LOCATION;
    }

}
