
package com.turkcell.balanceinquiry.ejb.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BalanceInquiryImpl", targetNamespace = "http://impl.ejb.balanceinquiry.turkcell.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BalanceInquiryImpl {


    /**
     * 
     * @param cacheDate
     * @param poOfferId
     * @return
     *     returns java.util.List<com.turkcell.balanceinquiry.ejb.impl.OfferRepresentation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCache", targetNamespace = "http://impl.ejb.balanceinquiry.turkcell.com/", className = "com.turkcell.balanceinquiry.ejb.impl.GetCache")
    @ResponseWrapper(localName = "getCacheResponse", targetNamespace = "http://impl.ejb.balanceinquiry.turkcell.com/", className = "com.turkcell.balanceinquiry.ejb.impl.GetCacheResponse")
    public List<OfferRepresentation> getCache(
        @WebParam(name = "poOfferId", targetNamespace = "")
        String poOfferId,
        @WebParam(name = "cacheDate", targetNamespace = "")
        XMLGregorianCalendar cacheDate);

    /**
     * 
     * @param channelName
     * @param msisdn
     * @param originTimeStamp
     * @param clientTransactionId
     * @param inquiryType
     * @return
     *     returns com.turkcell.balanceinquiry.ejb.impl.GetBalancesResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomerBalances", targetNamespace = "http://impl.ejb.balanceinquiry.turkcell.com/", className = "com.turkcell.balanceinquiry.ejb.impl.GetCustomerBalances")
    @ResponseWrapper(localName = "getCustomerBalancesResponse", targetNamespace = "http://impl.ejb.balanceinquiry.turkcell.com/", className = "com.turkcell.balanceinquiry.ejb.impl.GetCustomerBalancesResponse")
    public GetBalancesResponse getCustomerBalances(
        @WebParam(name = "msisdn", targetNamespace = "")
        String msisdn,
        @WebParam(name = "clientTransactionId", targetNamespace = "")
        String clientTransactionId,
        @WebParam(name = "originTimeStamp", targetNamespace = "")
        XMLGregorianCalendar originTimeStamp,
        @WebParam(name = "inquiryType", targetNamespace = "")
        int inquiryType,
        @WebParam(name = "channelName", targetNamespace = "")
        String channelName);

    /**
     * 
     * @param channelName
     * @param msisdn
     * @param originTimeStamp
     * @param clientTransactionId
     * @param inquiryType
     * @return
     *     returns com.turkcell.balanceinquiry.ejb.impl.GetBalancesResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomerBalancesWithHistory", targetNamespace = "http://impl.ejb.balanceinquiry.turkcell.com/", className = "com.turkcell.balanceinquiry.ejb.impl.GetCustomerBalancesWithHistory")
    @ResponseWrapper(localName = "getCustomerBalancesWithHistoryResponse", targetNamespace = "http://impl.ejb.balanceinquiry.turkcell.com/", className = "com.turkcell.balanceinquiry.ejb.impl.GetCustomerBalancesWithHistoryResponse")
    public GetBalancesResponse getCustomerBalancesWithHistory(
        @WebParam(name = "msisdn", targetNamespace = "")
        String msisdn,
        @WebParam(name = "clientTransactionId", targetNamespace = "")
        String clientTransactionId,
        @WebParam(name = "originTimeStamp", targetNamespace = "")
        XMLGregorianCalendar originTimeStamp,
        @WebParam(name = "inquiryType", targetNamespace = "")
        int inquiryType,
        @WebParam(name = "channelName", targetNamespace = "")
        String channelName);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "clearAllCache", targetNamespace = "http://impl.ejb.balanceinquiry.turkcell.com/", className = "com.turkcell.balanceinquiry.ejb.impl.ClearAllCache")
    @ResponseWrapper(localName = "clearAllCacheResponse", targetNamespace = "http://impl.ejb.balanceinquiry.turkcell.com/", className = "com.turkcell.balanceinquiry.ejb.impl.ClearAllCacheResponse")
    public void clearAllCache();

    /**
     * 
     * @param poOfferId
     */
    @WebMethod
    @RequestWrapper(localName = "clearCacheFor", targetNamespace = "http://impl.ejb.balanceinquiry.turkcell.com/", className = "com.turkcell.balanceinquiry.ejb.impl.ClearCacheFor")
    @ResponseWrapper(localName = "clearCacheForResponse", targetNamespace = "http://impl.ejb.balanceinquiry.turkcell.com/", className = "com.turkcell.balanceinquiry.ejb.impl.ClearCacheForResponse")
    public void clearCacheFor(
        @WebParam(name = "poOfferId", targetNamespace = "")
        List<Long> poOfferId);

}
