
package com.euromsg.ws.auth;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuthHttpGet", targetNamespace = "http://ws.euromsg.com/auth")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthHttpGet {


    /**
     * Logon the system.
     * 
     * @param password
     * @param username
     * @return
     *     returns com.euromsg.ws.auth.EmAuthResult
     */
    @WebMethod(operationName = "Login")
    @WebResult(name = "EmAuthResult", targetNamespace = "http://ws.euromsg.com/auth", partName = "Body")
    public EmAuthResult login(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Username")
        String username,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Password")
        String password);

    /**
     * Logoff the system.
     * 
     * @param serviceTicket
     * @return
     *     returns com.euromsg.ws.auth.EmAuthResult
     */
    @WebMethod(operationName = "Logout")
    @WebResult(name = "EmAuthResult", targetNamespace = "http://ws.euromsg.com/auth", partName = "Body")
    public EmAuthResult logout(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ServiceTicket")
        String serviceTicket);

}
