
package com.euromsg.ws.auth;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuthSoap", targetNamespace = "http://ws.euromsg.com/auth")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthSoap {


    /**
     * Logon the system.
     * 
     * @param password
     * @param username
     * @return
     *     returns com.euromsg.ws.auth.EmAuthResult
     */
    @WebMethod(operationName = "Login", action = "http://ws.euromsg.com/auth/Login")
    @WebResult(name = "LoginResult", targetNamespace = "http://ws.euromsg.com/auth")
    @RequestWrapper(localName = "Login", targetNamespace = "http://ws.euromsg.com/auth", className = "com.euromsg.ws.auth.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://ws.euromsg.com/auth", className = "com.euromsg.ws.auth.LoginResponse")
    public EmAuthResult login(
        @WebParam(name = "Username", targetNamespace = "http://ws.euromsg.com/auth")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://ws.euromsg.com/auth")
        String password);

    /**
     * Logoff the system.
     * 
     * @param serviceTicket
     * @return
     *     returns com.euromsg.ws.auth.EmAuthResult
     */
    @WebMethod(operationName = "Logout", action = "http://ws.euromsg.com/auth/Logout")
    @WebResult(name = "LogoutResult", targetNamespace = "http://ws.euromsg.com/auth")
    @RequestWrapper(localName = "Logout", targetNamespace = "http://ws.euromsg.com/auth", className = "com.euromsg.ws.auth.Logout")
    @ResponseWrapper(localName = "LogoutResponse", targetNamespace = "http://ws.euromsg.com/auth", className = "com.euromsg.ws.auth.LogoutResponse")
    public EmAuthResult logout(
        @WebParam(name = "ServiceTicket", targetNamespace = "http://ws.euromsg.com/auth")
        String serviceTicket);

}
