
package com.euromsg.ws.post;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PostSoap", targetNamespace = "http://ws.euromsg.com/post")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PostSoap {


    /**
     * Enables free-html posting.
     * 
     * @param charset
     * @param htmlBody
     * @param attachments
     * @param toName
     * @param subject
     * @param toEmailAddress
     * @param fromName
     * @param fromAddress
     * @param serviceTicket
     * @param replyAddress
     * @return
     *     returns com.euromsg.ws.post.EmPostResult
     */
    @WebMethod(operationName = "PostHtml", action = "http://ws.euromsg.com/post/PostHtml")
    @WebResult(name = "PostHtmlResult", targetNamespace = "http://ws.euromsg.com/post")
    @RequestWrapper(localName = "PostHtml", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.PostHtml")
    @ResponseWrapper(localName = "PostHtmlResponse", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.PostHtmlResponse")
    public EmPostResult postHtml(
        @WebParam(name = "ServiceTicket", targetNamespace = "http://ws.euromsg.com/post")
        String serviceTicket,
        @WebParam(name = "FromName", targetNamespace = "http://ws.euromsg.com/post")
        String fromName,
        @WebParam(name = "FromAddress", targetNamespace = "http://ws.euromsg.com/post")
        String fromAddress,
        @WebParam(name = "ReplyAddress", targetNamespace = "http://ws.euromsg.com/post")
        String replyAddress,
        @WebParam(name = "Subject", targetNamespace = "http://ws.euromsg.com/post")
        String subject,
        @WebParam(name = "HtmlBody", targetNamespace = "http://ws.euromsg.com/post")
        String htmlBody,
        @WebParam(name = "Charset", targetNamespace = "http://ws.euromsg.com/post")
        String charset,
        @WebParam(name = "ToName", targetNamespace = "http://ws.euromsg.com/post")
        String toName,
        @WebParam(name = "ToEmailAddress", targetNamespace = "http://ws.euromsg.com/post")
        String toEmailAddress,
        @WebParam(name = "Attachments", targetNamespace = "http://ws.euromsg.com/post")
        ArrayOfEmAttachment attachments);

    /**
     * Enables free-html posting with CC and BCC. Be aware that these CC and BCC emails may affect the reporting of transactional emails. Please use them after consulting euro.message IT Team.
     * 
     * @param charset
     * @param htmlBody
     * @param attachments
     * @param toName
     * @param subject
     * @param toEmailAddress
     * @param fromName
     * @param fromAddress
     * @param serviceTicket
     * @param replyAddress
     * @param ccEmailAddress
     * @param bccEmailAddress
     * @return
     *     returns com.euromsg.ws.post.EmPostResult
     */
    @WebMethod(operationName = "PostHtmlWithCCandBCC", action = "http://ws.euromsg.com/post/PostHtmlWithCCandBCC")
    @WebResult(name = "PostHtmlWithCCandBCCResult", targetNamespace = "http://ws.euromsg.com/post")
    @RequestWrapper(localName = "PostHtmlWithCCandBCC", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.PostHtmlWithCCandBCC")
    @ResponseWrapper(localName = "PostHtmlWithCCandBCCResponse", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.PostHtmlWithCCandBCCResponse")
    public EmPostResult postHtmlWithCCandBCC(
        @WebParam(name = "ServiceTicket", targetNamespace = "http://ws.euromsg.com/post")
        String serviceTicket,
        @WebParam(name = "FromName", targetNamespace = "http://ws.euromsg.com/post")
        String fromName,
        @WebParam(name = "FromAddress", targetNamespace = "http://ws.euromsg.com/post")
        String fromAddress,
        @WebParam(name = "ReplyAddress", targetNamespace = "http://ws.euromsg.com/post")
        String replyAddress,
        @WebParam(name = "Subject", targetNamespace = "http://ws.euromsg.com/post")
        String subject,
        @WebParam(name = "HtmlBody", targetNamespace = "http://ws.euromsg.com/post")
        String htmlBody,
        @WebParam(name = "Charset", targetNamespace = "http://ws.euromsg.com/post")
        String charset,
        @WebParam(name = "ToName", targetNamespace = "http://ws.euromsg.com/post")
        String toName,
        @WebParam(name = "ToEmailAddress", targetNamespace = "http://ws.euromsg.com/post")
        String toEmailAddress,
        @WebParam(name = "CCEmailAddress", targetNamespace = "http://ws.euromsg.com/post")
        String ccEmailAddress,
        @WebParam(name = "BCCEmailAddress", targetNamespace = "http://ws.euromsg.com/post")
        String bccEmailAddress,
        @WebParam(name = "Attachments", targetNamespace = "http://ws.euromsg.com/post")
        ArrayOfEmAttachment attachments);

    /**
     * Enables free-html posting with type
     * 
     * @param charset
     * @param htmlBody
     * @param attachments
     * @param toName
     * @param postType
     * @param subject
     * @param toEmailAddress
     * @param fromName
     * @param fromAddress
     * @param serviceTicket
     * @param replyAddress
     * @return
     *     returns com.euromsg.ws.post.EmPostResult
     */
    @WebMethod(operationName = "PostHtmlWithType", action = "http://ws.euromsg.com/post/PostHtmlWithType")
    @WebResult(name = "PostHtmlWithTypeResult", targetNamespace = "http://ws.euromsg.com/post")
    @RequestWrapper(localName = "PostHtmlWithType", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.PostHtmlWithType")
    @ResponseWrapper(localName = "PostHtmlWithTypeResponse", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.PostHtmlWithTypeResponse")
    public EmPostResult postHtmlWithType(
        @WebParam(name = "ServiceTicket", targetNamespace = "http://ws.euromsg.com/post")
        String serviceTicket,
        @WebParam(name = "FromName", targetNamespace = "http://ws.euromsg.com/post")
        String fromName,
        @WebParam(name = "FromAddress", targetNamespace = "http://ws.euromsg.com/post")
        String fromAddress,
        @WebParam(name = "ReplyAddress", targetNamespace = "http://ws.euromsg.com/post")
        String replyAddress,
        @WebParam(name = "Subject", targetNamespace = "http://ws.euromsg.com/post")
        String subject,
        @WebParam(name = "HtmlBody", targetNamespace = "http://ws.euromsg.com/post")
        String htmlBody,
        @WebParam(name = "Charset", targetNamespace = "http://ws.euromsg.com/post")
        String charset,
        @WebParam(name = "ToName", targetNamespace = "http://ws.euromsg.com/post")
        String toName,
        @WebParam(name = "ToEmailAddress", targetNamespace = "http://ws.euromsg.com/post")
        String toEmailAddress,
        @WebParam(name = "Attachments", targetNamespace = "http://ws.euromsg.com/post")
        ArrayOfEmAttachment attachments,
        @WebParam(name = "PostType", targetNamespace = "http://ws.euromsg.com/post")
        String postType);

    /**
     * Enables free-html posting with type with CC and BCC. Be aware that these CC and BCC emails may affect the reporting of transactional emails. Please use them after consulting euro.message IT Team.
     * 
     * @param charset
     * @param attachments
     * @param postType
     * @param subject
     * @param serviceTicket
     * @param htmlBody
     * @param toName
     * @param toEmailAddress
     * @param fromName
     * @param fromAddress
     * @param replyAddress
     * @param ccEmailAddress
     * @param bccEmailAddress
     * @return
     *     returns com.euromsg.ws.post.EmPostResult
     */
    @WebMethod(operationName = "PostHtmlWithTypeCCandBCC", action = "http://ws.euromsg.com/post/PostHtmlWithTypeCCandBCC")
    @WebResult(name = "PostHtmlWithTypeCCandBCCResult", targetNamespace = "http://ws.euromsg.com/post")
    @RequestWrapper(localName = "PostHtmlWithTypeCCandBCC", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.PostHtmlWithTypeCCandBCC")
    @ResponseWrapper(localName = "PostHtmlWithTypeCCandBCCResponse", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.PostHtmlWithTypeCCandBCCResponse")
    public EmPostResult postHtmlWithTypeCCandBCC(
        @WebParam(name = "ServiceTicket", targetNamespace = "http://ws.euromsg.com/post")
        String serviceTicket,
        @WebParam(name = "FromName", targetNamespace = "http://ws.euromsg.com/post")
        String fromName,
        @WebParam(name = "FromAddress", targetNamespace = "http://ws.euromsg.com/post")
        String fromAddress,
        @WebParam(name = "ReplyAddress", targetNamespace = "http://ws.euromsg.com/post")
        String replyAddress,
        @WebParam(name = "Subject", targetNamespace = "http://ws.euromsg.com/post")
        String subject,
        @WebParam(name = "HtmlBody", targetNamespace = "http://ws.euromsg.com/post")
        String htmlBody,
        @WebParam(name = "Charset", targetNamespace = "http://ws.euromsg.com/post")
        String charset,
        @WebParam(name = "ToName", targetNamespace = "http://ws.euromsg.com/post")
        String toName,
        @WebParam(name = "ToEmailAddress", targetNamespace = "http://ws.euromsg.com/post")
        String toEmailAddress,
        @WebParam(name = "CCEmailAddress", targetNamespace = "http://ws.euromsg.com/post")
        String ccEmailAddress,
        @WebParam(name = "BCCEmailAddress", targetNamespace = "http://ws.euromsg.com/post")
        String bccEmailAddress,
        @WebParam(name = "Attachments", targetNamespace = "http://ws.euromsg.com/post")
        ArrayOfEmAttachment attachments,
        @WebParam(name = "PostType", targetNamespace = "http://ws.euromsg.com/post")
        String postType);

    /**
     * Enables free-html posting with type, key_id and custom fields
     * 
     * @param charset
     * @param attachments
     * @param postType
     * @param customParams
     * @param subject
     * @param keyID
     * @param serviceTicket
     * @param htmlBody
     * @param toName
     * @param toEmailAddress
     * @param fromName
     * @param fromAddress
     * @param replyAddress
     * @return
     *     returns com.euromsg.ws.post.EmPostResult
     */
    @WebMethod(operationName = "PostHtmlWithTypeKeyIDAndCustomParams", action = "http://ws.euromsg.com/post/PostHtmlWithTypeKeyIDAndCustomParams")
    @WebResult(name = "PostHtmlWithTypeKeyIDAndCustomParamsResult", targetNamespace = "http://ws.euromsg.com/post")
    @RequestWrapper(localName = "PostHtmlWithTypeKeyIDAndCustomParams", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.PostHtmlWithTypeKeyIDAndCustomParams")
    @ResponseWrapper(localName = "PostHtmlWithTypeKeyIDAndCustomParamsResponse", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.PostHtmlWithTypeKeyIDAndCustomParamsResponse")
    public EmPostResult postHtmlWithTypeKeyIDAndCustomParams(
        @WebParam(name = "ServiceTicket", targetNamespace = "http://ws.euromsg.com/post")
        String serviceTicket,
        @WebParam(name = "FromName", targetNamespace = "http://ws.euromsg.com/post")
        String fromName,
        @WebParam(name = "FromAddress", targetNamespace = "http://ws.euromsg.com/post")
        String fromAddress,
        @WebParam(name = "ReplyAddress", targetNamespace = "http://ws.euromsg.com/post")
        String replyAddress,
        @WebParam(name = "Subject", targetNamespace = "http://ws.euromsg.com/post")
        String subject,
        @WebParam(name = "HtmlBody", targetNamespace = "http://ws.euromsg.com/post")
        String htmlBody,
        @WebParam(name = "Charset", targetNamespace = "http://ws.euromsg.com/post")
        String charset,
        @WebParam(name = "ToName", targetNamespace = "http://ws.euromsg.com/post")
        String toName,
        @WebParam(name = "ToEmailAddress", targetNamespace = "http://ws.euromsg.com/post")
        String toEmailAddress,
        @WebParam(name = "Attachments", targetNamespace = "http://ws.euromsg.com/post")
        ArrayOfEmAttachment attachments,
        @WebParam(name = "PostType", targetNamespace = "http://ws.euromsg.com/post")
        String postType,
        @WebParam(name = "KeyID", targetNamespace = "http://ws.euromsg.com/post")
        String keyID,
        @WebParam(name = "CustomParams", targetNamespace = "http://ws.euromsg.com/post")
        String customParams);

    /**
     * Enables transactional template html posting.
     * 
     * @param charset
     * @param attachments
     * @param templateName
     * @param toName
     * @param bodyVariables
     * @param toEmailAddress
     * @param subjectVariables
     * @param fromName
     * @param fromAddress
     * @param serviceTicket
     * @param replyAddress
     * @return
     *     returns com.euromsg.ws.post.EmPostResult
     */
    @WebMethod(operationName = "PostTransactionalEmailWithHtmlTemplate", action = "http://ws.euromsg.com/post/PostTransactionalEmailWithHtmlTemplate")
    @WebResult(name = "PostTransactionalEmailWithHtmlTemplateResult", targetNamespace = "http://ws.euromsg.com/post")
    @RequestWrapper(localName = "PostTransactionalEmailWithHtmlTemplate", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.PostTransactionalEmailWithHtmlTemplate")
    @ResponseWrapper(localName = "PostTransactionalEmailWithHtmlTemplateResponse", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.PostTransactionalEmailWithHtmlTemplateResponse")
    public EmPostResult postTransactionalEmailWithHtmlTemplate(
        @WebParam(name = "ServiceTicket", targetNamespace = "http://ws.euromsg.com/post")
        String serviceTicket,
        @WebParam(name = "FromName", targetNamespace = "http://ws.euromsg.com/post")
        String fromName,
        @WebParam(name = "FromAddress", targetNamespace = "http://ws.euromsg.com/post")
        String fromAddress,
        @WebParam(name = "ReplyAddress", targetNamespace = "http://ws.euromsg.com/post")
        String replyAddress,
        @WebParam(name = "TemplateName", targetNamespace = "http://ws.euromsg.com/post")
        String templateName,
        @WebParam(name = "SubjectVariables", targetNamespace = "http://ws.euromsg.com/post")
        ArrayOfEmKeyValue subjectVariables,
        @WebParam(name = "BodyVariables", targetNamespace = "http://ws.euromsg.com/post")
        ArrayOfEmKeyValue bodyVariables,
        @WebParam(name = "Charset", targetNamespace = "http://ws.euromsg.com/post")
        String charset,
        @WebParam(name = "ToName", targetNamespace = "http://ws.euromsg.com/post")
        String toName,
        @WebParam(name = "ToEmailAddress", targetNamespace = "http://ws.euromsg.com/post")
        String toEmailAddress,
        @WebParam(name = "Attachments", targetNamespace = "http://ws.euromsg.com/post")
        ArrayOfEmAttachment attachments);

    /**
     * Enables transactional template html posting.
     * 
     * @param charset
     * @param attachments
     * @param templateName
     * @param toName
     * @param xml
     * @param toEmailAddress
     * @param fromName
     * @param fromAddress
     * @param serviceTicket
     * @param replyAddress
     * @return
     *     returns com.euromsg.ws.post.EmPostResult
     */
    @WebMethod(operationName = "PostTransactionalEmailWithXsltTemplate", action = "http://ws.euromsg.com/post/PostTransactionalEmailWithXsltTemplate")
    @WebResult(name = "PostTransactionalEmailWithXsltTemplateResult", targetNamespace = "http://ws.euromsg.com/post")
    @RequestWrapper(localName = "PostTransactionalEmailWithXsltTemplate", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.PostTransactionalEmailWithXsltTemplate")
    @ResponseWrapper(localName = "PostTransactionalEmailWithXsltTemplateResponse", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.PostTransactionalEmailWithXsltTemplateResponse")
    public EmPostResult postTransactionalEmailWithXsltTemplate(
        @WebParam(name = "ServiceTicket", targetNamespace = "http://ws.euromsg.com/post")
        String serviceTicket,
        @WebParam(name = "FromName", targetNamespace = "http://ws.euromsg.com/post")
        String fromName,
        @WebParam(name = "FromAddress", targetNamespace = "http://ws.euromsg.com/post")
        String fromAddress,
        @WebParam(name = "ReplyAddress", targetNamespace = "http://ws.euromsg.com/post")
        String replyAddress,
        @WebParam(name = "TemplateName", targetNamespace = "http://ws.euromsg.com/post")
        String templateName,
        @WebParam(name = "Xml", targetNamespace = "http://ws.euromsg.com/post")
        String xml,
        @WebParam(name = "Charset", targetNamespace = "http://ws.euromsg.com/post")
        String charset,
        @WebParam(name = "ToName", targetNamespace = "http://ws.euromsg.com/post")
        String toName,
        @WebParam(name = "ToEmailAddress", targetNamespace = "http://ws.euromsg.com/post")
        String toEmailAddress,
        @WebParam(name = "Attachments", targetNamespace = "http://ws.euromsg.com/post")
        ArrayOfEmAttachment attachments);

    /**
     * Enables transactional template html posting.
     * 
     * @param charset
     * @param attachments
     * @param templateName
     * @param toName
     * @param xml
     * @param toEmailAddress
     * @param fromName
     * @param fromAddress
     * @param serviceTicket
     * @param replyAddress
     * @return
     *     returns com.euromsg.ws.post.EmPostResult
     */
    @WebMethod(operationName = "PostTransactionalEmailWithXsltTemplate2", action = "http://ws.euromsg.com/post/PostTransactionalEmailWithXsltTemplate2")
    @WebResult(name = "PostTransactionalEmailWithXsltTemplate2Result", targetNamespace = "http://ws.euromsg.com/post")
    @RequestWrapper(localName = "PostTransactionalEmailWithXsltTemplate2", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.PostTransactionalEmailWithXsltTemplate2")
    @ResponseWrapper(localName = "PostTransactionalEmailWithXsltTemplate2Response", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.PostTransactionalEmailWithXsltTemplate2Response")
    public EmPostResult postTransactionalEmailWithXsltTemplate2(
        @WebParam(name = "ServiceTicket", targetNamespace = "http://ws.euromsg.com/post")
        String serviceTicket,
        @WebParam(name = "FromName", targetNamespace = "http://ws.euromsg.com/post")
        String fromName,
        @WebParam(name = "FromAddress", targetNamespace = "http://ws.euromsg.com/post")
        String fromAddress,
        @WebParam(name = "ReplyAddress", targetNamespace = "http://ws.euromsg.com/post")
        String replyAddress,
        @WebParam(name = "TemplateName", targetNamespace = "http://ws.euromsg.com/post")
        String templateName,
        @WebParam(name = "Xml", targetNamespace = "http://ws.euromsg.com/post")
        String xml,
        @WebParam(name = "Charset", targetNamespace = "http://ws.euromsg.com/post")
        String charset,
        @WebParam(name = "ToName", targetNamespace = "http://ws.euromsg.com/post")
        String toName,
        @WebParam(name = "ToEmailAddress", targetNamespace = "http://ws.euromsg.com/post")
        String toEmailAddress,
        @WebParam(name = "Attachments", targetNamespace = "http://ws.euromsg.com/post")
        ArrayOfEmAttachment attachments);

    /**
     * Gets Delivery Report For A Transactional Message
     * 
     * @param postID
     * @param serviceTicket
     * @return
     *     returns com.euromsg.ws.post.EmPostResult
     */
    @WebMethod(operationName = "GetPostResult", action = "http://ws.euromsg.com/post/GetPostResult")
    @WebResult(name = "GetPostResultResult", targetNamespace = "http://ws.euromsg.com/post")
    @RequestWrapper(localName = "GetPostResult", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.GetPostResult")
    @ResponseWrapper(localName = "GetPostResultResponse", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.GetPostResultResponse")
    public EmPostResult getPostResult(
        @WebParam(name = "ServiceTicket", targetNamespace = "http://ws.euromsg.com/post")
        String serviceTicket,
        @WebParam(name = "PostID", targetNamespace = "http://ws.euromsg.com/post")
        String postID);

    /**
     * Gets Bulk Result For Transacrtional Messages Between Two Dates
     * 
     * @param beginDate
     * @param endDate
     * @param bulkReport
     * @param serviceTicket
     * @param getPostBulkResultResult
     */
    @WebMethod(operationName = "GetPostBulkResult", action = "http://ws.euromsg.com/post/GetPostBulkResult")
    @RequestWrapper(localName = "GetPostBulkResult", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.GetPostBulkResult")
    @ResponseWrapper(localName = "GetPostBulkResultResponse", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.GetPostBulkResultResponse")
    public void getPostBulkResult(
        @WebParam(name = "ServiceTicket", targetNamespace = "http://ws.euromsg.com/post")
        String serviceTicket,
        @WebParam(name = "BeginDate", targetNamespace = "http://ws.euromsg.com/post")
        String beginDate,
        @WebParam(name = "EndDate", targetNamespace = "http://ws.euromsg.com/post")
        String endDate,
        @WebParam(name = "GetPostBulkResultResult", targetNamespace = "http://ws.euromsg.com/post", mode = WebParam.Mode.OUT)
        Holder<EmPostResult> getPostBulkResultResult,
        @WebParam(name = "BulkReport", targetNamespace = "http://ws.euromsg.com/post", mode = WebParam.Mode.OUT)
        Holder<ArrayOfEmPostBulkReport> bulkReport);

    /**
     * Gets Bulk Result For Transactional Messages Between Two Dates and Optional Post Type and To Adress
     * 
     * @param beginDateStr
     * @param postType
     * @param getPostBulkResultWithOptionalResult
     * @param bulkReport
     * @param serviceTicket
     * @param toAddress
     * @param endDateStr
     */
    @WebMethod(operationName = "GetPostBulkResultWithOptional", action = "http://ws.euromsg.com/post/GetPostBulkResultWithOptional")
    @RequestWrapper(localName = "GetPostBulkResultWithOptional", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.GetPostBulkResultWithOptional")
    @ResponseWrapper(localName = "GetPostBulkResultWithOptionalResponse", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.GetPostBulkResultWithOptionalResponse")
    public void getPostBulkResultWithOptional(
        @WebParam(name = "serviceTicket", targetNamespace = "http://ws.euromsg.com/post")
        String serviceTicket,
        @WebParam(name = "beginDateStr", targetNamespace = "http://ws.euromsg.com/post")
        String beginDateStr,
        @WebParam(name = "endDateStr", targetNamespace = "http://ws.euromsg.com/post")
        String endDateStr,
        @WebParam(name = "postType", targetNamespace = "http://ws.euromsg.com/post")
        String postType,
        @WebParam(name = "toAddress", targetNamespace = "http://ws.euromsg.com/post")
        String toAddress,
        @WebParam(name = "GetPostBulkResultWithOptionalResult", targetNamespace = "http://ws.euromsg.com/post", mode = WebParam.Mode.OUT)
        Holder<EmPostResult> getPostBulkResultWithOptionalResult,
        @WebParam(name = "BulkReport", targetNamespace = "http://ws.euromsg.com/post", mode = WebParam.Mode.OUT)
        Holder<ArrayOfEmPostBulkReport> bulkReport);

    /**
     * Gets Bulk Result For Transactional Messages Between Two Dates and Custom Params
     * 
     * @param beginDateStr
     * @param customParams
     * @param serviceTicket
     * @param bulkReports
     * @param endDateStr
     * @param getPostBulkResultWithCustomParamsResult
     */
    @WebMethod(operationName = "GetPostBulkResultWithCustomParams", action = "http://ws.euromsg.com/post/GetPostBulkResultWithCustomParams")
    @RequestWrapper(localName = "GetPostBulkResultWithCustomParams", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.GetPostBulkResultWithCustomParams")
    @ResponseWrapper(localName = "GetPostBulkResultWithCustomParamsResponse", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.GetPostBulkResultWithCustomParamsResponse")
    public void getPostBulkResultWithCustomParams(
        @WebParam(name = "serviceTicket", targetNamespace = "http://ws.euromsg.com/post")
        String serviceTicket,
        @WebParam(name = "beginDateStr", targetNamespace = "http://ws.euromsg.com/post")
        String beginDateStr,
        @WebParam(name = "endDateStr", targetNamespace = "http://ws.euromsg.com/post")
        String endDateStr,
        @WebParam(name = "customParams", targetNamespace = "http://ws.euromsg.com/post")
        String customParams,
        @WebParam(name = "GetPostBulkResultWithCustomParamsResult", targetNamespace = "http://ws.euromsg.com/post", mode = WebParam.Mode.OUT)
        Holder<EmPostResult> getPostBulkResultWithCustomParamsResult,
        @WebParam(name = "bulkReports", targetNamespace = "http://ws.euromsg.com/post", mode = WebParam.Mode.OUT)
        Holder<ArrayOfEmPostBulkReport> bulkReports);

    /**
     * Gets Delivery Report For  Transactional Messages,out parameter give the messages results.
     * 
     * @param postIds
     * @param getPostBulkResultByPostIdResult
     * @param serviceTicket
     * @param bulkResult
     */
    @WebMethod(operationName = "GetPostBulkResultByPostId", action = "http://ws.euromsg.com/post/GetPostBulkResultByPostId")
    @RequestWrapper(localName = "GetPostBulkResultByPostId", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.GetPostBulkResultByPostId")
    @ResponseWrapper(localName = "GetPostBulkResultByPostIdResponse", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.GetPostBulkResultByPostIdResponse")
    public void getPostBulkResultByPostId(
        @WebParam(name = "serviceTicket", targetNamespace = "http://ws.euromsg.com/post")
        String serviceTicket,
        @WebParam(name = "postIds", targetNamespace = "http://ws.euromsg.com/post")
        ArrayOfString postIds,
        @WebParam(name = "GetPostBulkResultByPostIdResult", targetNamespace = "http://ws.euromsg.com/post", mode = WebParam.Mode.OUT)
        Holder<EmPostResult> getPostBulkResultByPostIdResult,
        @WebParam(name = "bulkResult", targetNamespace = "http://ws.euromsg.com/post", mode = WebParam.Mode.OUT)
        Holder<ArrayOfEmPostResult> bulkResult);

    /**
     * Gets Bulk Bounce Result For Transacrtional Messages Between Two Dates
     * 
     * @param beginDate
     * @param endDate
     * @param bulkReport
     * @param getPostBulkBounceResultResult
     * @param serviceTicket
     */
    @WebMethod(operationName = "GetPostBulkBounceResult", action = "http://ws.euromsg.com/post/GetPostBulkBounceResult")
    @RequestWrapper(localName = "GetPostBulkBounceResult", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.GetPostBulkBounceResult")
    @ResponseWrapper(localName = "GetPostBulkBounceResultResponse", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.GetPostBulkBounceResultResponse")
    public void getPostBulkBounceResult(
        @WebParam(name = "ServiceTicket", targetNamespace = "http://ws.euromsg.com/post")
        String serviceTicket,
        @WebParam(name = "BeginDate", targetNamespace = "http://ws.euromsg.com/post")
        String beginDate,
        @WebParam(name = "EndDate", targetNamespace = "http://ws.euromsg.com/post")
        String endDate,
        @WebParam(name = "GetPostBulkBounceResultResult", targetNamespace = "http://ws.euromsg.com/post", mode = WebParam.Mode.OUT)
        Holder<EmPostResult> getPostBulkBounceResultResult,
        @WebParam(name = "BulkReport", targetNamespace = "http://ws.euromsg.com/post", mode = WebParam.Mode.OUT)
        Holder<ArrayOfEmPostBulkReport> bulkReport);

    /**
     * Gets Bulk Result For Transacrtional Messages Between Two Last Update Dates
     * 
     * @param beginDate
     * @param endDate
     * @param getPostBulkResultByLastUpdateResult
     * @param bulkReport
     * @param serviceTicket
     */
    @WebMethod(operationName = "GetPostBulkResultByLastUpdate", action = "http://ws.euromsg.com/post/GetPostBulkResultByLastUpdate")
    @RequestWrapper(localName = "GetPostBulkResultByLastUpdate", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.GetPostBulkResultByLastUpdate")
    @ResponseWrapper(localName = "GetPostBulkResultByLastUpdateResponse", targetNamespace = "http://ws.euromsg.com/post", className = "com.euromsg.ws.post.GetPostBulkResultByLastUpdateResponse")
    public void getPostBulkResultByLastUpdate(
        @WebParam(name = "ServiceTicket", targetNamespace = "http://ws.euromsg.com/post")
        String serviceTicket,
        @WebParam(name = "BeginDate", targetNamespace = "http://ws.euromsg.com/post")
        String beginDate,
        @WebParam(name = "EndDate", targetNamespace = "http://ws.euromsg.com/post")
        String endDate,
        @WebParam(name = "GetPostBulkResultByLastUpdateResult", targetNamespace = "http://ws.euromsg.com/post", mode = WebParam.Mode.OUT)
        Holder<EmPostResult> getPostBulkResultByLastUpdateResult,
        @WebParam(name = "BulkReport", targetNamespace = "http://ws.euromsg.com/post", mode = WebParam.Mode.OUT)
        Holder<ArrayOfEmPostBulkReport> bulkReport);

}
