
package com.euromsg.ws.post;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PostHttpPost", targetNamespace = "http://ws.euromsg.com/post")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PostHttpPost {


    /**
     * Gets Delivery Report For A Transactional Message
     * 
     * @param postID
     * @param serviceTicket
     * @return
     *     returns com.euromsg.ws.post.EmPostResult
     */
    @WebMethod(operationName = "GetPostResult")
    @WebResult(name = "EmPostResult", targetNamespace = "http://ws.euromsg.com/post", partName = "Body")
    public EmPostResult getPostResult(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ServiceTicket")
        String serviceTicket,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "PostID")
        String postID);

}
