
package com.euromsg.ws.post;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Post", targetNamespace = "http://ws.euromsg.com/post", wsdlLocation = "META-INF/wsdl/Post.wsdl")
public class Post
    extends Service
{

    private final static URL POST_WSDL_LOCATION;
    private final static WebServiceException POST_EXCEPTION;
    private final static QName POST_QNAME = new QName("http://ws.euromsg.com/post", "Post");

    static {
        POST_WSDL_LOCATION = com.euromsg.ws.post.Post.class.getClassLoader().getResource("META-INF/wsdl/Post.wsdl");
        WebServiceException e = null;
        if (POST_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/Post.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        POST_EXCEPTION = e;
    }

    public Post() {
        super(__getWsdlLocation(), POST_QNAME);
    }

    public Post(WebServiceFeature... features) {
        super(__getWsdlLocation(), POST_QNAME, features);
    }

    public Post(URL wsdlLocation) {
        super(wsdlLocation, POST_QNAME);
    }

    public Post(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POST_QNAME, features);
    }

    public Post(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Post(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PostSoap
     */
    @WebEndpoint(name = "PostSoap")
    public PostSoap getPostSoap() {
        return super.getPort(new QName("http://ws.euromsg.com/post", "PostSoap"), PostSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostSoap
     */
    @WebEndpoint(name = "PostSoap")
    public PostSoap getPostSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.euromsg.com/post", "PostSoap"), PostSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns PostSoap
     */
    @WebEndpoint(name = "PostSoap12")
    public PostSoap getPostSoap12() {
        return super.getPort(new QName("http://ws.euromsg.com/post", "PostSoap12"), PostSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostSoap
     */
    @WebEndpoint(name = "PostSoap12")
    public PostSoap getPostSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.euromsg.com/post", "PostSoap12"), PostSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns PostHttpGet
     */
    @WebEndpoint(name = "PostHttpGet")
    public PostHttpGet getPostHttpGet() {
        return super.getPort(new QName("http://ws.euromsg.com/post", "PostHttpGet"), PostHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostHttpGet
     */
    @WebEndpoint(name = "PostHttpGet")
    public PostHttpGet getPostHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.euromsg.com/post", "PostHttpGet"), PostHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns PostHttpPost
     */
    @WebEndpoint(name = "PostHttpPost")
    public PostHttpPost getPostHttpPost() {
        return super.getPort(new QName("http://ws.euromsg.com/post", "PostHttpPost"), PostHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostHttpPost
     */
    @WebEndpoint(name = "PostHttpPost")
    public PostHttpPost getPostHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.euromsg.com/post", "PostHttpPost"), PostHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POST_EXCEPTION!= null) {
            throw POST_EXCEPTION;
        }
        return POST_WSDL_LOCATION;
    }

}
