
package com.turkcell.marsalman.camman.webservices.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.turkcell.marsalman.camman.common.data.model.ArrayOfOffer;
import com.turkcell.marsalman.camman.common.data.model.ArrayOfOfferSimplified;
import com.turkcell.marsalman.camman.common.data.model.ArrayOfOfferWithRank;
import com.turkcell.marsalman.camman.common.data.model.PaymentPlanType;
import com.turkcell.marsalman.camman.common.data.model.WriteXResponseResult;
import com.turkcell.marsalman.camman.common.data.model.campaigndefinition.CampaignsDefinitionType;
import com.turkcell.marsalman.camman.common.data.model.campaigndefinition.PriceDefinitionsType;
import com.turkcell.marsalman.camman.webservices.data.model.GetInboundOffersResult;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OfferServicePortType", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
@XmlSeeAlso({
    com.turkcell.marsalman.camman.webservices.service.ObjectFactory.class,
    com.turkcell.marsalman.camman.common.data.model.ObjectFactory.class,
    com.turkcell.marsalman.camman.common.data.model.campaigndefinition.ObjectFactory.class,
    com.turkcell.marsalman.camman.webservices.data.model.ObjectFactory.class
})
public interface OfferServicePortType {


    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in9
     * @param in5
     * @param in6
     * @param in7
     * @param in8
     * @return
     *     returns com.turkcell.marsalman.camman.common.data.model.ArrayOfOffer
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
    @RequestWrapper(localName = "getAvailableOffers", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetAvailableOffers")
    @ResponseWrapper(localName = "getAvailableOffersResponse", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetAvailableOffersResponse")
    public ArrayOfOffer getAvailableOffers(
        @WebParam(name = "in0", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        boolean in6,
        @WebParam(name = "in7", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        boolean in7,
        @WebParam(name = "in8", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        Integer in8,
        @WebParam(name = "in9", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        Integer in9);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in9
     * @param in5
     * @param in6
     * @param in7
     * @param in8
     * @return
     *     returns com.turkcell.marsalman.camman.common.data.model.ArrayOfOffer
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
    @RequestWrapper(localName = "getAvailableOffers2", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetAvailableOffers2")
    @ResponseWrapper(localName = "getAvailableOffers2Response", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetAvailableOffers2Response")
    public ArrayOfOffer getAvailableOffers2(
        @WebParam(name = "in0", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        boolean in6,
        @WebParam(name = "in7", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        boolean in7,
        @WebParam(name = "in8", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        Integer in8,
        @WebParam(name = "in9", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        Integer in9);

    /**
     * 
     * @param transactionType
     * @param campaignId
     * @param mainOfferId
     * @param channel
     * @param detailOfferIdList
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
    @RequestWrapper(localName = "getContractTextForOffers", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetContractTextForOffers")
    @ResponseWrapper(localName = "getContractTextForOffersResponse", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetContractTextForOffersResponse")
    public String getContractTextForOffers(
        @WebParam(name = "campaignId", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        Long campaignId,
        @WebParam(name = "mainOfferId", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        Long mainOfferId,
        @WebParam(name = "detailOfferIdList", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        ArrayOfLong detailOfferIdList,
        @WebParam(name = "channel", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        int channel,
        @WebParam(name = "transactionType", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String transactionType);

    /**
     * 
     * @return
     *     returns com.turkcell.marsalman.camman.webservices.service.ArrayOfString
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
    @RequestWrapper(localName = "getCurrentGAOCacheObjectsStr", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetCurrentGAOCacheObjectsStr")
    @ResponseWrapper(localName = "getCurrentGAOCacheObjectsStrResponse", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetCurrentGAOCacheObjectsStrResponse")
    public ArrayOfString getCurrentGAOCacheObjectsStr();

    /**
     * 
     * @param campaignId
     * @param msisdn
     * @param offerId
     * @return
     *     returns com.turkcell.marsalman.camman.common.data.model.campaigndefinition.PriceDefinitionsType
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
    @RequestWrapper(localName = "getPriceDefinitionsForCampOfr", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetPriceDefinitionsForCampOfr")
    @ResponseWrapper(localName = "getPriceDefinitionsForCampOfrResponse", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetPriceDefinitionsForCampOfrResponse")
    public PriceDefinitionsType getPriceDefinitionsForCampOfr(
        @WebParam(name = "msisdn", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String msisdn,
        @WebParam(name = "campaignId", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        Long campaignId,
        @WebParam(name = "offerId", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        Long offerId);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in9
     * @param in10
     * @param in5
     * @param in6
     * @param in7
     * @param in8
     * @return
     *     returns com.turkcell.marsalman.camman.common.data.model.ArrayOfOfferWithRank
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
    @RequestWrapper(localName = "getAvailableOffersWithRank", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetAvailableOffersWithRank")
    @ResponseWrapper(localName = "getAvailableOffersWithRankResponse", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetAvailableOffersWithRankResponse")
    public ArrayOfOfferWithRank getAvailableOffersWithRank(
        @WebParam(name = "in0", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        boolean in6,
        @WebParam(name = "in7", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        boolean in7,
        @WebParam(name = "in8", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        Integer in8,
        @WebParam(name = "in9", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        Integer in9,
        @WebParam(name = "in10", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        boolean in10);

    /**
     * 
     * @param in2
     * @param in1
     * @param in3
     * @param in0
     * @return
     *     returns com.turkcell.marsalman.camman.common.data.model.ArrayOfOfferSimplified
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
    @RequestWrapper(localName = "getInboundOffers", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetInboundOffers")
    @ResponseWrapper(localName = "getInboundOffersResponse", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetInboundOffersResponse")
    public ArrayOfOfferSimplified getInboundOffers(
        @WebParam(name = "in0", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        Integer in2,
        @WebParam(name = "in3", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        int in3);

    /**
     * 
     * @param transactionType
     * @param oldObligationIdList
     * @param msisdn
     * @param obligatoryFilter
     * @param maxOfferCount
     * @param channel
     * @return
     *     returns com.turkcell.marsalman.camman.webservices.data.model.GetInboundOffersResult
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
    @RequestWrapper(localName = "getInboundOffersWithSwitchMapping", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetInboundOffersWithSwitchMapping")
    @ResponseWrapper(localName = "getInboundOffersWithSwitchMappingResponse", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetInboundOffersWithSwitchMappingResponse")
    public GetInboundOffersResult getInboundOffersWithSwitchMapping(
        @WebParam(name = "msisdn", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String msisdn,
        @WebParam(name = "channel", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String channel,
        @WebParam(name = "maxOfferCount", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        Integer maxOfferCount,
        @WebParam(name = "obligatoryFilter", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        int obligatoryFilter,
        @WebParam(name = "transactionType", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String transactionType,
        @WebParam(name = "oldObligationIdList", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        ArrayOfLong oldObligationIdList);

    /**
     * 
     * @return
     *     returns com.turkcell.marsalman.camman.webservices.service.AnyType2AnyTypeMap
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
    @RequestWrapper(localName = "getRunningGAOCacheParameters", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetRunningGAOCacheParameters")
    @ResponseWrapper(localName = "getRunningGAOCacheParametersResponse", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetRunningGAOCacheParametersResponse")
    public AnyType2AnyTypeMap getRunningGAOCacheParameters();

    /**
     * 
     * @param in2
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
    @RequestWrapper(localName = "getContractText", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetContractText")
    @ResponseWrapper(localName = "getContractTextResponse", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetContractTextResponse")
    public String getContractText(
        @WebParam(name = "in0", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        Long in0,
        @WebParam(name = "in1", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        Long in1,
        @WebParam(name = "in2", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        Long in2);

    /**
     * 
     * @param in0
     * @return
     *     returns com.turkcell.marsalman.camman.common.data.model.campaigndefinition.PriceDefinitionsType
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
    @RequestWrapper(localName = "getPriceDefinitions", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetPriceDefinitions")
    @ResponseWrapper(localName = "getPriceDefinitionsResponse", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetPriceDefinitionsResponse")
    public PriceDefinitionsType getPriceDefinitions(
        @WebParam(name = "in0", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in0);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in14
     * @param in0
     * @param in11
     * @param in9
     * @param in10
     * @param in13
     * @param in12
     * @param in5
     * @param in6
     * @param in7
     * @param in8
     * @return
     *     returns com.turkcell.marsalman.camman.common.data.model.WriteXResponseResult
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
    @RequestWrapper(localName = "writeXResponse", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.WriteXResponse")
    @ResponseWrapper(localName = "writeXResponseResponse", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.WriteXResponseResponse")
    public WriteXResponseResult writeXResponse(
        @WebParam(name = "in0", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        Long in0,
        @WebParam(name = "in1", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        Long in2,
        @WebParam(name = "in3", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in7,
        @WebParam(name = "in8", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in8,
        @WebParam(name = "in9", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in9,
        @WebParam(name = "in10", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in10,
        @WebParam(name = "in11", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in11,
        @WebParam(name = "in12", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in12,
        @WebParam(name = "in13", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in13,
        @WebParam(name = "in14", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        boolean in14);

    /**
     * 
     * @param in2
     * @param in1
     * @param in3
     * @param in0
     * @return
     *     returns com.turkcell.marsalman.camman.common.data.model.PaymentPlanType
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
    @RequestWrapper(localName = "getPaymentPlan", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetPaymentPlan")
    @ResponseWrapper(localName = "getPaymentPlanResponse", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetPaymentPlanResponse")
    public PaymentPlanType getPaymentPlan(
        @WebParam(name = "in0", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        Long in1,
        @WebParam(name = "in2", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        ArrayOfLong in2,
        @WebParam(name = "in3", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
        Long in3);

    /**
     * 
     * @return
     *     returns com.turkcell.marsalman.camman.common.data.model.campaigndefinition.CampaignsDefinitionType
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com")
    @RequestWrapper(localName = "getCampaignDefinitions", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetCampaignDefinitions")
    @ResponseWrapper(localName = "getCampaignDefinitionsResponse", targetNamespace = "http://service.webservices.camman.marsalman.turkcell.com", className = "com.turkcell.marsalman.camman.webservices.service.GetCampaignDefinitionsResponse")
    public CampaignsDefinitionType getCampaignDefinitions();

}
