
package com.turkcell.crm.sfa.service.endpoints;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PositionServiceEndPoint", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PositionServiceEndPoint {


    /**
     * 
     * @param checkAccSalesTeamRequest
     * @return
     *     returns com.turkcell.crm.sfa.service.endpoints.CheckAccSalesTeamResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "checkAccSalesTeamResponse", targetNamespace = "")
    @RequestWrapper(localName = "checkAccSalesTeamByNcstByLdapName", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.CheckAccSalesTeamByNcstByLdapName")
    @ResponseWrapper(localName = "checkAccSalesTeamByNcstByLdapNameResponse", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.CheckAccSalesTeamByNcstByLdapNameResponse")
    public CheckAccSalesTeamResponse checkAccSalesTeamByNcstByLdapName(
        @WebParam(name = "checkAccSalesTeamRequest", targetNamespace = "")
        CheckAccSalesTeamRequest checkAccSalesTeamRequest)
        throws Exception_Exception
    ;

    /**
     * 
     * @param accountsPortfolioRequest
     * @return
     *     returns com.turkcell.crm.sfa.service.endpoints.AccountsPortfolioResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "accountsPortfolioResponse", targetNamespace = "")
    @RequestWrapper(localName = "getAccountsPortfolioByNcst", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetAccountsPortfolioByNcst")
    @ResponseWrapper(localName = "getAccountsPortfolioByNcstResponse", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetAccountsPortfolioByNcstResponse")
    public AccountsPortfolioResponse getAccountsPortfolioByNcst(
        @WebParam(name = "accountsPortfolioRequest", targetNamespace = "")
        AccountsPortfolioRequest accountsPortfolioRequest)
        throws Exception_Exception
    ;

    /**
     * 
     * @param customerPrimaryUpperHierarchyGetRequest
     * @return
     *     returns com.turkcell.crm.sfa.service.endpoints.CustomerPrimaryUpperHierarchyGetResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "customerPrimaryUpperHierarchyGetResponse", targetNamespace = "")
    @RequestWrapper(localName = "getCustomerPrimaryUpperHierarchy", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetCustomerPrimaryUpperHierarchy")
    @ResponseWrapper(localName = "getCustomerPrimaryUpperHierarchyResponse", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetCustomerPrimaryUpperHierarchyResponse")
    public CustomerPrimaryUpperHierarchyGetResponse getCustomerPrimaryUpperHierarchy(
        @WebParam(name = "customerPrimaryUpperHierarchyGetRequest", targetNamespace = "")
        CustomerPrimaryUpperHierarchyGetRequest customerPrimaryUpperHierarchyGetRequest)
        throws Exception_Exception
    ;

    /**
     * 
     * @param customerUkstOrTeleSalesUpperHierarchyGetRequest
     * @return
     *     returns com.turkcell.crm.sfa.service.endpoints.CustomerUkstOrTeleSalesUpperHierarchyGetResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "customerUkstOrTeleSalesUpperHierarchyGetResponse", targetNamespace = "")
    @RequestWrapper(localName = "getCustomerUkstOrTeleSalesUpperHierarchy", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetCustomerUkstOrTeleSalesUpperHierarchy")
    @ResponseWrapper(localName = "getCustomerUkstOrTeleSalesUpperHierarchyResponse", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetCustomerUkstOrTeleSalesUpperHierarchyResponse")
    public CustomerUkstOrTeleSalesUpperHierarchyGetResponse getCustomerUkstOrTeleSalesUpperHierarchy(
        @WebParam(name = "customerUkstOrTeleSalesUpperHierarchyGetRequest", targetNamespace = "")
        CustomerUkstOrTeleSalesUpperHierarchyGetRequest customerUkstOrTeleSalesUpperHierarchyGetRequest)
        throws Exception_Exception
    ;

    /**
     * 
     * @param getDealerInfoNFRequest
     * @return
     *     returns com.turkcell.crm.sfa.service.endpoints.GetDealerInfoNetFlowResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "getDealerInfoNFResponse", targetNamespace = "")
    @RequestWrapper(localName = "getDealerInfoNF", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetDealerInfoNF")
    @ResponseWrapper(localName = "getDealerInfoNFResponse", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetDealerInfoNFResponse")
    public GetDealerInfoNetFlowResponse getDealerInfoNF(
        @WebParam(name = "GetDealerInfoNFRequest", targetNamespace = "")
        GetDealerInfoNetFlowRequest getDealerInfoNFRequest)
        throws Exception_Exception
    ;

    /**
     * 
     * @param getPositionDetailNFRequest
     * @return
     *     returns com.turkcell.crm.sfa.service.endpoints.GetPositionDetailNetFlowResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "getPositionDetailNFResponse", targetNamespace = "")
    @RequestWrapper(localName = "getPositionDetailNF", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetPositionDetailNF")
    @ResponseWrapper(localName = "getPositionDetailNFResponse", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetPositionDetailNFResponse")
    public GetPositionDetailNetFlowResponse getPositionDetailNF(
        @WebParam(name = "GetPositionDetailNFRequest", targetNamespace = "")
        GetPositionDetailNetFlowRequest getPositionDetailNFRequest)
        throws Exception_Exception
    ;

    /**
     * 
     * @param positionDetailsRequest
     * @return
     *     returns com.turkcell.crm.sfa.service.endpoints.PositionDetailsResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "positionDetailsResponse", targetNamespace = "")
    @RequestWrapper(localName = "getPositionDetails", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetPositionDetails")
    @ResponseWrapper(localName = "getPositionDetailsResponse", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetPositionDetailsResponse")
    public PositionDetailsResponse getPositionDetails(
        @WebParam(name = "positionDetailsRequest", targetNamespace = "")
        PositionDetailsRequest positionDetailsRequest)
        throws Exception_Exception
    ;

    /**
     * 
     * @param getPositionDetailWithNcstRequest
     * @return
     *     returns com.turkcell.crm.sfa.service.endpoints.GetPositionDetailByNcstResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "getPositionDetailWithNcstResponse", targetNamespace = "")
    @RequestWrapper(localName = "getPositionDetailWithNcst", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetPositionDetailWithNcst")
    @ResponseWrapper(localName = "getPositionDetailWithNcstResponse", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetPositionDetailWithNcstResponse")
    public GetPositionDetailByNcstResponse getPositionDetailWithNcst(
        @WebParam(name = "GetPositionDetailWithNcstRequest", targetNamespace = "")
        GetPositionDetailByNcstRequest getPositionDetailWithNcstRequest)
        throws Exception_Exception
    ;

    /**
     * 
     * @param getPositionHierarchyNFRequest
     * @return
     *     returns com.turkcell.crm.sfa.service.endpoints.GetPositionHierarchyNetFlowResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "getPositionHierarchyNFResponse", targetNamespace = "")
    @RequestWrapper(localName = "getPositionHierarchyNF", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetPositionHierarchyNF")
    @ResponseWrapper(localName = "getPositionHierarchyNFResponse", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetPositionHierarchyNFResponse")
    public GetPositionHierarchyNetFlowResponse getPositionHierarchyNF(
        @WebParam(name = "GetPositionHierarchyNFRequest", targetNamespace = "")
        GetPositionHierarchyNetFlowRequest getPositionHierarchyNFRequest)
        throws Exception_Exception
    ;

    /**
     * 
     * @param positionLowerHierarchyRequest
     * @return
     *     returns com.turkcell.crm.sfa.service.endpoints.PositionLowerHierarchyResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "positionLowerHierarchyResponse", targetNamespace = "")
    @RequestWrapper(localName = "getPositionLowerHierarchy", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetPositionLowerHierarchy")
    @ResponseWrapper(localName = "getPositionLowerHierarchyResponse", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetPositionLowerHierarchyResponse")
    public PositionLowerHierarchyResponse getPositionLowerHierarchy(
        @WebParam(name = "positionLowerHierarchyRequest", targetNamespace = "")
        PositionLowerHierarchyRequest positionLowerHierarchyRequest)
        throws Exception_Exception
    ;

    /**
     * 
     * @param solPositionHierarchyRequest
     * @return
     *     returns com.turkcell.crm.sfa.service.endpoints.SolPositionHierarchyResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "SOLPositionHierarchyResponse", targetNamespace = "")
    @RequestWrapper(localName = "getSOLPositionHierarchy", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetSOLPositionHierarchy")
    @ResponseWrapper(localName = "getSOLPositionHierarchyResponse", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetSOLPositionHierarchyResponse")
    public SolPositionHierarchyResponse getSOLPositionHierarchy(
        @WebParam(name = "SOLPositionHierarchyRequest", targetNamespace = "")
        SolPositionHierarchyRequest solPositionHierarchyRequest)
        throws Exception_Exception
    ;

    /**
     * 
     * @param subOrganizationRequest
     * @return
     *     returns com.turkcell.crm.sfa.service.endpoints.SubOrganizationResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "subOrganizationResponse", targetNamespace = "")
    @RequestWrapper(localName = "getSubOrganizationsByOrganizationName", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetSubOrganizationsByOrganizationName")
    @ResponseWrapper(localName = "getSubOrganizationsByOrganizationNameResponse", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.GetSubOrganizationsByOrganizationNameResponse")
    public SubOrganizationResponse getSubOrganizationsByOrganizationName(
        @WebParam(name = "subOrganizationRequest", targetNamespace = "")
        SubOrganizationRequest subOrganizationRequest)
        throws Exception_Exception
    ;

    /**
     * 
     * @param positionSearchRequest
     * @return
     *     returns com.turkcell.crm.sfa.service.endpoints.PositionSearchResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "positionSearchResponse", targetNamespace = "")
    @RequestWrapper(localName = "searchPositions", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.SearchPositions")
    @ResponseWrapper(localName = "searchPositionsResponse", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/", className = "com.turkcell.crm.sfa.service.endpoints.SearchPositionsResponse")
    public PositionSearchResponse searchPositions(
        @WebParam(name = "positionSearchRequest", targetNamespace = "")
        PositionSearchRequest positionSearchRequest)
        throws Exception_Exception
    ;

}
