package com.turkcell.crm.sfa.service.endpoints;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PositionService", targetNamespace = "http://endpoints.service.sfa.crm.turkcell.com/",
		wsdlLocation = "http://extstablews.sd.turkcell.com.tr/tsfaws/PositionService?wsdl")
public class PositionService
		extends Service
{

	private final static URL POSITIONSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.turkcell.crm.sfa.service.endpoints.PositionService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.turkcell.crm.sfa.service.endpoints.PositionService.class.getResource(".");
			url = new URL(baseUrl, "http://extstablews.sd.turkcell.com.tr/tsfaws/PositionService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://extstablews.sd.turkcell.com.tr/tsfaws/PositionService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		POSITIONSERVICE_WSDL_LOCATION = url;
	}

	public PositionService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public PositionService() {
		super(POSITIONSERVICE_WSDL_LOCATION, new QName("http://endpoints.service.sfa.crm.turkcell.com/", "PositionService"));
	}

	/**
	 * 
	 * @return returns PositionServiceEndPoint
	 */
	@WebEndpoint(name = "PositionServiceEndPointPort")
	public PositionServiceEndPoint getPositionServiceEndPointPort() {
		return super.getPort(new QName("http://endpoints.service.sfa.crm.turkcell.com/", "PositionServiceEndPointPort"), PositionServiceEndPoint.class);
	}

	/**
	 * 
	 * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code> parameter
	 *        will have their default values.
	 * @return returns PositionServiceEndPoint
	 */
	@WebEndpoint(name = "PositionServiceEndPointPort")
	public PositionServiceEndPoint getPositionServiceEndPointPort(WebServiceFeature... features) {
		return super.getPort(new QName("http://endpoints.service.sfa.crm.turkcell.com/", "PositionServiceEndPointPort"), PositionServiceEndPoint.class,
				features);
	}

}
