package com.deneme;

public enum LogProcess {

	REMEMBERME,
	ACCOUNT,
	CELLULAR,
	MC,
	ACCOUNT_MC,
	GSM_PASSWORD,
	ACCOUNT_GSM_PASSWORD,
	EMAIL_PASSWORD,
	ACCOUNT_EMAIL_PASSWORD,
	TRANSFER_USER,
	OLD_DB,
	//
	START_LOGIN,
	GET_APP_CONFIG,
	GET_LOGIN_TYPE,
	GET_LOGIN_TYPE_FOR_ACCOUNT,
	START_MC_LOGIN,
	CAPTCHA,
	GET_ACCOUNT_LIST,
	REMOVE_ACCOUNT,
	LOGOUT_ACCOUNT,
	SUSPICIOUS_TOKEN_DELETE,
	GET_TRANSFER_TOKEN,
	//
	REGISTER,
	SEND_OTP,
	VERIFY_OTP,
	VALIDATE_EMAIL,
	UPDATE_MSISDN,
	UPDATE_MSISDN_SEND_OTP,
	UPDATE_MSISDN_VERIFY_OTP,
	UPDATE_EMAIL,
	//
	FORGET_ME,
	PASSWORD_CHANGE,
	PASSWORD_CHANGE_SHOW,
	PASSWORD_CHANGE_WEB,
	SEND_PASSWORD_CHANGE_LINK,
	//
	UPDATE_REGISTERED_EMAIL,
	SAVE_DIGITALID,
	//
	VALIDATION;

}
